name: Ubuntu runner
run-name: is automated testing

on:
  push:
    branches:
      - master

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup ssh
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}
      - name: Deploy to VPS
        run: ssh -o StrictHostKeyChecking=no root@154.197.124.66 " cd /path/to/your/project && git pull origin main && npm run build && pm2 restart ecosystem.config.mjs"
